theme: jekyll-theme-hacker

# Site settings
title: Walk on the web flow
description: the goal is to leave some links that seem interesting to me (but also to share them)
show_downloads: false
author: snonov

#baseurl: "https://snonov.github.io/"
url: "https://snonov.github.io"

# Permet à jekyll-github-metadata de résoudre site.github en local
repository: snonov/snonov.github.io

# Plugins activés (tous fournis par la gem github-pages)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
