theme: jekyll-theme-hacker

# Site settings
title: Walk on the web flow
description: purpose is to leave here some interesting to me (but also share them) links
show_downloads: false

#baseurl: "https://snonov.github.io/"
url: "https://snonov.github.io/"
